# Generated by Django 2.0.4 on 2018-07-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='img',
            field=models.ImageField(default='users/image/default_big_14.png', upload_to='video/image/%Y/%m', verbose_name='Attach a greaat picture for your post'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=100, verbose_name='video name'),
        ),
    ]
